plugins:

  cfy_rms:
    executor: central_deployment_agent
    package_name: cloudify-simple-rms-plugin
    source: source
    package_version: '0.0.1'

node_types:

  cloudify.rms.node:
    derived_from: cloudify.nodes.Root
    properties:
      resource_pool:
        default: default_pool
    interfaces:
      create:
        implementation: cfy_rms.cloudify_simple_rms.tasks.allocate
          inputs:
            resource_pool:
              default: { get_property : [SELF, resource_pool ] }

      delete:
        implementation: cfy_rms.cloudify_simple_rms.tasks.release
          inputs:
            resource_pool:
              default: { get_property : [SELF, resource_pool ] }
